# keras变量操作
* 操作建立在tenserflow上
* 用variable包变量，用eval查看tensor里的值

In [1]:
import keras.backend as k
import numpy as np

Using TensorFlow backend.


## 1 定义两个变量

In [2]:
t1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
t2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
t1 = k.variable(t1)
t2 = k.variable(t2)
print(t1, t2)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref> <tf.Variable 'Variable_1:0' shape=(2, 3) dtype=float32_ref>


## 2 concatenate
    要拼接的装在列表里
    指定axis在哪个维度拼接

In [3]:
t_concat = k.concatenate([t1, t2], axis=1)
k.eval(t_concat)

array([[  1.,   2.,   3.,   7.,   8.,   9.],
       [  4.,   5.,   6.,  10.,  11.,  12.]], dtype=float32)

## 3 切片
    可以直接像Python一样切

In [4]:
print(t_concat)
t_concat1 = t_concat[:, ::2]

Tensor("concat:0", shape=(2, 6), dtype=float32)


In [5]:
k.eval(t_concat1)

array([[  1.,   3.,   8.],
       [  4.,   6.,  11.]], dtype=float32)

## 4 增加/减小/交换维度
    增加维度用 expand_dims
    减小维度用 squeeze
    交换维度用 transpose

In [6]:
# 增加维度
t_unsq = k.expand_dims(t1, 1)
print(t_unsq)
k.eval(t_unsq)

Tensor("ExpandDims:0", shape=(2, 1, 3), dtype=float32)


array([[[ 1.,  2.,  3.]],

       [[ 4.,  5.,  6.]]], dtype=float32)

In [7]:
# 减小维度
t_sq = k.squeeze(t_unsq, 1)
print(t_sq)
k.eval(t_sq)

Tensor("Squeeze:0", shape=(2, 3), dtype=float32)


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [8]:
# 交换维度
# 第一步，先把t1增加一个维度[2, 3] --> [2, 1, 3]
t_tr = k.expand_dims(t1, 1)
print(k.eval(t_tr))
print(t_tr.shape)
# 第二步，交换维度[2, 1, 3] --> [3, 1, 2]
t_tr2 = k.transpose(t_tr) # 这里的keras后端没有perm参数，但是tf是有perm参数的，可以定义重新排列的维度顺序
print(k.eval(t_tr2))
print(t_tr2.shape)

[[[ 1.  2.  3.]]

 [[ 4.  5.  6.]]]
(2, 1, 3)
[[[ 1.  4.]]

 [[ 2.  5.]]

 [[ 3.  6.]]]
(3, 1, 2)
